# Generated by Django 4.0.4 on 2022-04-14 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price_per_hour', models.BooleanField()),
                ('price', models.IntegerField(default=0)),
                ('scanned_file', models.FileField(upload_to='sv/images')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scanned_file', models.FileField(upload_to='bs/images')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.service')),
            ],
        ),
    ]
